esphome:
  name: photo-frame
  friendly_name: Photo Frame
  project:
    name: ahadi.epd_photo_frame
    version: 1.0.0
  on_boot:
    priority: -100
    then:
      - wait_until:
          condition: wifi.connected
          timeout: 30s
      - wait_until:
          condition: api.connected
          timeout: 20s
      # Start background download and wait for success
      - lambda: |-
          id(epd_display).startDownload();
      - wait_until:
          condition:
            binary_sensor.is_on: dl_ok
          timeout: 180s
      - if:
          condition:
            binary_sensor.is_on: dl_ok
          then:
            - lambda: |-
                id(epd_display).displayFromFile();
      # Power off display before deep sleep
      - lambda: |-
          id(epd_display).sleepDisplay();
      - delay: 200ms
      # Sleep for configured minutes
      - deep_sleep.enter:
          id: epd_sleep
          sleep_duration: !lambda |-
            float mins = id(wake_interval_minutes).state;
            if (mins < 0.0167f) mins = 1.0f;  // min ~1s
            if (mins > (30.0f * 24.0f * 60.0f)) mins = (30.0f * 24.0f * 60.0f);  // clamp 30d
            return (uint32_t)(mins * 60.0f * 1000.0f);

esp32:
  board: esp32dev
  framework:
    type: esp-idf
  # Use custom partitions with SPIFFS (single app + spiffs large)
  partitions: partitions.csv

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "o/UlT22K9GgWOo6lOChF+bMMvAWnsWctPv3b/abIUCc="
  services:
    - service: set_image_url
      variables:
        url: string
      then:
        - lambda: |-
            id(epd_display).setImageUrl(std::string(url));
    - service: download_image
      then:
        - lambda: 'id(epd_display).startDownload();'
    - service: display_image
      then:
        - lambda: 'id(epd_display).displayFromFile();'

ota:
  - platform: esphome
    password: "b90f12e39aade3f5a99cc36c909af902"

# Time sync for scheduling sleep-until
time:
  - platform: sntp
    id: sntp_time

  # keep for logs if needed; not required for interval sleep

# Manual deep sleep control (sleep only when triggered)
deep_sleep:
  id: epd_sleep
  # wakeup_pin: GPIO32
  # wakeup_pin_mode: IGNORE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Photo-Frame Fallback Hotspot"
    password: "Pvwqos4MOApr"

external_components:
  # - source: github://amir-hadi/esphome-waveshare-13.3-epd@main
  #   components: [ epd_photo_frame ]
  - source:
      type: local
      path: components
    components: [ epd_photo_frame ]

captive_portal:

# Enable SPI
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14
  miso_pin: GPIO19

# Your EPD Photo Frame component
display:
  - platform: epd_photo_frame
    id: epd_display
    reset_pin: GPIO26
    dc_pin: GPIO27
    busy_pin: GPIO25
    power_pin: GPIO33
    cs_master_pin: GPIO18
    cs_slave_pin: GPIO22
    image_url: "http://10.0.0.253:8080/image.bin"
    update_interval: 30min
    download_success:
      id: dl_ok
      name: "EPD Download Success"
      entity_category: diagnostic

    download_bytes:
      id: dl_bytes
      name: "EPD Download Bytes"
      entity_category: diagnostic

    download_status:
      id: dl_status
      name: "EPD Download Status"
      entity_category: diagnostic

number:
  - platform: template
    id: wake_interval_minutes
    name: "EPD Wake Interval (min)"
    min_value: 1
    max_value: 1440
    step: 1
    optimistic: true
    entity_category: config
    initial_value: 240
    restore_value: true

button:
  - platform: template
    name: "EPD Download Image"
    icon: mdi:download
    on_press:
      then:
        - lambda: |-
            id(epd_display).startDownload();

  - platform: template
    name: "EPD Refresh From File"
    icon: mdi:image-refresh
    on_press:
      then:
        - lambda: |-
            id(epd_display).displayFromFile();

  - platform: template
    id: epd_sleep_interval_btn
    name: "EPD Sleep (Interval)"
    icon: mdi:sleep
    on_press:
      then:
        - deep_sleep.enter:
            id: epd_sleep
            sleep_duration: !lambda |-
              float mins = id(wake_interval_minutes).state;
              if (mins < 0.0167f) mins = 0.0167f;  // >= 1s
              return (uint32_t)(mins * 60.0f * 1000.0f);

binary_sensor:
  - platform: status
    id: epd_status
    name: "Photo Frame Status"   # must set a name so HA exposes it



## Optional: Add a text sensor to show current image URL (commented to keep build minimal)
# text_sensor:
#   - platform: custom
#     lambda: |-
#       auto url_sensor = new esphome::text_sensor::TextSensor();
#       url_sensor->publish_state(id(epd_display).getImageUrl());
#       return {url_sensor};
#     text_sensors:
#       - name: "Current Image URL"
#         id: current_image_url